# Generated by Django 6.0.4 on 2026-04-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monetary reward amount in ₹', max_digits=10),
        ),
    ]
