# Generated by Django 6.0.4 on 2026-04-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monetary reward in ₹ for completing this task', max_digits=10),
        ),
    ]
